name: Quality Checks

env:
  NODE_VERSION: 20.16.0
  PNPM_VERSION: 9.7.0

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - main

concurrency:
  group: checkCodeQuality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkCodeQuality:
    name: "Quality Checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup project"
        uses: ./.github/actions/setup-project

      - name: "Check code quality"
        uses: ./.github/actions/check-quality
